---

- name: Prepare RHPDS workshop environment with all "Ansible Basics" exercises
  hosts: localhost
  vars:
    # Input controller host and password here or via extra_vars."
    controller_host: https://ansible-1.9pbg8.sandbox1407.opentlc.com 
    controller_password: "NjYyNzUz"
  roles:
    - automation-platform
