---

- name: Prepare RHPDS workshop environment with all "Ansible Basics" exercises
  hosts: localhost
  vars:
    # Input controller host and password here or via extra_vars."
    controller_host: https://ansible-1.fd9pf.sandbox2472.opentlc.com
    controller_password: "NDc1NzU1"
  roles:
    - automation-platform
