---

- name: Prepare Demo environment with service user
  hosts: web
  become: true
  gather_facts: false
  vars:
    ansible_user: "{{ lookup('env', 'USER') }}"
  pre_tasks:
    - name: Ensure SSH password is provided  # noqa run-once[task]
      ansible.builtin.assert:
        that:
          - ansible_password is defined
          - ansible_password | length > 0
        quiet: true
        fail_msg: "No SSH password is provided. Run the playbook with '--ask-pass'."
      run_once: true
  tasks:
    - name: Create Ansible service user
      ansible.builtin.user:
        name: ansible
        state: present

    - name: Distribute public key of {{ ansible_user }} to service user  # noqa name[template]
      ansible.posix.authorized_key:
        user: ansible
        key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
        state: present

    - name: Add password-less sudo permissions for Ansible service user
      ansible.builtin.copy:
        content: "ansible ALL=(ALL) NOPASSWD:ALL"
        dest: /etc/sudoers.d/automation
        validate: /usr/sbin/visudo -csf %s
        mode: "0644"

- name: Adjust inventory file on Ansible control node
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  vars:
    lab_user: "{{ lookup('env', 'USER') }}"
  tasks:
    - name: Add variable section for web group with ansible_user
      community.general.ini_file:
        path: "/home/{{ lab_user }}/lab_inventory/hosts"
        section: web:vars
        option: ansible_user
        value: ansible
        no_extra_spaces: true
        mode: "0644"

    - name: Add variable section for control group with ansible_connection
      community.general.ini_file:
        path: "/home/{{ lab_user }}/lab_inventory/hosts"
        section: control:vars
        option: ansible_connection
        value: local
        no_extra_spaces: true
        mode: "0644"
