---

- name: "Test NetBox modules"
  hosts: localhost
  gather_facts: false
  vars:
    workshop_slug: rh6f44
    student_id: 2
  module_defaults:
    group/netbox.netbox.netbox:
      netbox_url: https://demo.netbox.dev/
      netbox_token: d126c7cdfdcecd469e230ad4014032f331e50110
  tasks:
    - name: Create site for Workshop
      netbox.netbox.netbox_site:
        data:
          name: RH Demo environment
          slug: rh_demo_environment
          status: Active
          region: Europe

    # It is expected that all managed nodes use the same OS, therefore only gathering from one host
    - name: Get facts of all servers in web group
      ansible.builtin.setup:
      delegate_to: "{{ item }}"
      delegate_facts: true
      loop: "{{ groups['web'] }}"

    - name: Add OS platform
      netbox.netbox.netbox_platform:
        data:
          name: "{{ os_distributor }} {{ os_version }}"
          slug: "{{ os_distributor | lower }}_{{ os_version }}"
      vars:
        os_distributor: "{{ hostvars[groups['web'][0]]['ansible_distribution'] }}"
        os_version: "{{ hostvars[groups['web'][0]]['ansible_distribution_major_version'] }}"

    - name: Create tenant group
      netbox.netbox.netbox_tenant_group:
        data:
          name: CC Workshop
          slug: cc_workshop
        state: present

## This is done by the attendees
    - name: Create tenant for my user
      netbox.netbox.netbox_tenant:
        data:
          name: "Student{{ student_id }}"
          slug: "student{{ student_id }}"
          description: Workshop Tenant of Student {{ student_id }}
          tenant_group: cc_workshop
        state: present

    - name: Create VM cluster
      netbox.netbox.netbox_cluster:
        data:
          name: Student {{ student_id }} VMs
          cluster_type: Amazon Web Services
          site: rh_demo_environment
          tenant: student{{ student_id }}

    - name: Create tag for Workshop VMs of Student {{ student_id }}
      netbox.netbox.netbox_tag:
        data:
          name: Student {{ student_id }} VM
          slug: student-{{ student_id }}-vm

    - name: Create VM
      netbox.netbox.netbox_virtual_machine:
        data:
          name: "{{ hostvars[item]['ansible_fqdn'] }}"
          site: rh_demo_environment
          cluster: Student {{ student_id }} VMs
          tenant: student{{ student_id }}
          platform: "{{ hostvars[item]['ansible_distribution'] | lower }}_{{ hostvars[item]['ansible_distribution_major_version'] }}"
          vcpus: "{{ hostvars[item]['ansible_processor_vcpus'] }}"
          memory: "{{ hostvars[item]['ansible_memtotal_mb'] }}"
          disk: "{{ hostvars[item]['ansible_devices']['nvme0n1']['size'] | split(' ') | first | int }}"
          virtual_machine_role: application-server
          status: Active
          tags:
            - student-{{ student_id }}-vm
        state: present
      loop: "{{ groups['web'] }}"
