---
- name: Capture Setup
  hosts: node1
  tasks:
    - name: Collect only specific facts
      ansible.builtin.setup:
        filter:
          - 'ansible_eth0'
          - 'ansible_*_mb'
      register: setup

    - ansible.builtin.debug:
        var: setup