---
- name: Create tenant
  cisco.aci.aci_tenant:
    host: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    use_ssl: true
    validate_certs: false
    name: demo-tenant-tg
    state: present
