---

- name: Ensure all hosts from Workshop inventory are enabled
  awx.awx.host:
    controller_host: "{{ controller_host }}"
    controller_username: admin
    controller_password: "{{ controller_password }}"
    name: "{{ item }}"
    inventory: Workshop Inventory
    enabled: true
    state: present
  loop:
    - ansible-1
    - node1
    - node2
    - node3
  tags: test

- name: Run ad-hoc ping command
  awx.awx.ad_hoc_command:
    controller_host: "{{ controller_host }}"
    controller_username: admin
    controller_password: "{{ controller_password }}"
    inventory: Workshop Inventory
    limit: "node1,node2,node3"
    module_name: ping
    execution_environment: Default execution environment
    credential: Workshop Credentials

- name: Run ad-hoc command to gather id
  awx.awx.ad_hoc_command:
    controller_host: "{{ controller_host }}"
    controller_username: admin
    controller_password: "{{ controller_password }}"
    inventory: Workshop Inventory
    limit: "node1,node2,node3"
    module_name: command
    module_args: id
    execution_environment: Default execution environment
    credential: Workshop Credentials

- name: Run ad-hoc command to print /etc/shadow
  awx.awx.ad_hoc_command:
    controller_host: "{{ controller_host }}"
    controller_username: admin
    controller_password: "{{ controller_password }}"
    inventory: Workshop Inventory
    limit: "node1,node2,node3"
    module_name: command
    module_args: cat /etc/shadow
    execution_environment: Default execution environment
    credential: Workshop Credentials
    become_enabled: true

- name: Run ad-hoc command to install tmux, this is the challenge lab
  awx.awx.ad_hoc_command:
    controller_host: "{{ controller_host }}"
    controller_username: admin
    controller_password: "{{ controller_password }}"
    inventory: Workshop Inventory
    limit: "node1,node2,node3"
    module_name: yum
    module_args: name=tmux
    execution_environment: Default execution environment
    credential: Workshop Credentials
    become_enabled: true
