---

- name: Ensure required variables are provided
  ansible.builtin.assert:
    that:
      - controller_host is defined
      - controller_host | length > 0
      - controller_password is defined
      - controller_password | length > 0
    quiet: true
    fail_msg: "Necessary variables are undefined! Provide them in the vars block or via extra_vars."

- ansible.builtin.import_tasks: ad-hoc-commands.yml  # noqa name[missing]
- ansible.builtin.import_tasks: projects-job-templates.yml  # noqa name[missing]
- ansible.builtin.import_tasks: surveys.yml  # noqa name[missing]
- ansible.builtin.import_tasks: rbac.yml  # noqa name[missing]
- ansible.builtin.import_tasks: workflows.yml  # noqa name[missing]
- ansible.builtin.import_tasks: wrap-up.yml  # noqa name[missing]
