---

- name: Create job template for survey demonstration
  awx.awx.job_template:
    controller_host: "{{ controller_host }}"
    controller_username: admin
    controller_password: "{{ controller_password }}"
    name: Create index.html
    job_type: run
    organization: Default
    inventory: Workshop Inventory
    project: Workshop Project
    execution_environment: Default execution environment
    playbook: rhel/apache/apache_role_install.yml
    credentials:
      - Workshop Credentials
    limit: web
    become_enabled: true
    survey_spec:
      name: survey
      description: Job template survey
      spec:
        - type: "text"
          question_name: "First Line"
          variable: first_line
          required: false
        - type: "text"
          question_name: "Second Line"
          variable: second_line
          required: false
    survey_enabled: true

- name: Run job template for survey demonstration, waiting for completion
  awx.awx.job_launch:
    controller_host: "{{ controller_host }}"
    controller_username: admin
    controller_password: "{{ controller_password }}"
    job_template: Create index.html
    extra_vars:
      first_line: "Ansible Automation is cool!"
      second_line: "Executed from a playbook outside of AAP."
    wait: true
