---

- name: Add "Webops Git Repo" project
  awx.awx.project:
    controller_host: "{{ controller_host }}"
    controller_username: admin
    controller_password: "{{ controller_password }}"
    name: Webops Git Repo
    organization: Default
    default_environment: Default execution environment
    scm_type: git
    scm_url: https://github.com/ansible/workshop-examples.git
    scm_branch: webops
    scm_update_on_launch: true
    scm_delete_on_update: true
    scm_clean: true
    state: present

- name: Add "Webdev Git Repo" project
  awx.awx.project:
    controller_host: "{{ controller_host }}"
    controller_username: admin
    controller_password: "{{ controller_password }}"
    name: Webdev Git Repo
    organization: Default
    default_environment: Default execution environment
    scm_type: git
    scm_url: https://github.com/ansible/workshop-examples.git
    scm_branch: webdev
    scm_update_on_launch: true
    scm_delete_on_update: true
    scm_clean: true
    state: present

- name: Create "Web App Deploy" job template
  awx.awx.job_template:
    controller_host: "{{ controller_host }}"
    controller_username: admin
    controller_password: "{{ controller_password }}"
    name: Web App Deploy
    job_type: run
    organization: Default
    inventory: Workshop Inventory
    project: Webops Git Repo
    execution_environment: Default execution environment
    playbook: rhel/webops/web_infrastructure.yml
    credentials:
      - Workshop Credentials
    limit: web
    become_enabled: true

- name: Create "Node.js Deploy" job template
  awx.awx.job_template:
    controller_host: "{{ controller_host }}"
    controller_username: admin
    controller_password: "{{ controller_password }}"
    name: Node.js Deploy
    job_type: run
    organization: Default
    inventory: Workshop Inventory
    project: Webdev Git Repo
    execution_environment: Default execution environment
    playbook: rhel/webdev/install_node_app.yml
    credentials:
      - Workshop Credentials
    limit: web
    become_enabled: true

- name: Create "Deploy Webapp Server" workflow
  awx.awx.workflow_job_template:
    controller_host: "{{ controller_host }}"
    controller_username: admin
    controller_password: "{{ controller_password }}"
    name: Deploy Webapp Server
    organization: Default
    workflow_nodes:
      - identifier: Web App Deploy
        unified_job_template:
          name: Web App Deploy
          type: job_template
        related:
          success_nodes:
            - identifier: Node.js Deploy
      - identifier: Node.js Deploy
        unified_job_template:
          name: Node.js Deploy
          type: job_template

- name: Run workflow template, waiting for completion
  awx.awx.workflow_launch:
    controller_host: "{{ controller_host }}"
    controller_username: admin
    controller_password: "{{ controller_password }}"
    workflow_template: Deploy Webapp Server
    wait: true
