---

- name: Create "Create Web Content" job template
  awx.awx.job_template:
    controller_host: "{{ controller_host }}"
    controller_username: admin
    controller_password: "{{ controller_password }}"
    name: Create Web Content
    job_type: run
    organization: Default
    inventory: Workshop Inventory
    project: Workshop Project
    execution_environment: Default execution environment
    playbook: rhel/apache/webcontent.yml
    credentials:
      - Workshop Credentials
    limit: web
    extra_vars:
      dev_content: "default dev content"
      prod_content: "default prod content"
    become_enabled: true

- name: Add inventory group
  awx.awx.group:
    controller_host: "{{ controller_host }}"
    controller_username: admin
    controller_password: "{{ controller_password }}"
    name: Webserver
    hosts:
      - node1
      - node2
      - node3
    inventory: Workshop Inventory
    variables:
      stage: dev
    state: present

- name: Flag node2 as stage prod host
  awx.awx.host:
    controller_host: "{{ controller_host }}"
    controller_username: admin
    controller_password: "{{ controller_password }}"
    inventory: Workshop Inventory
    name: node2
    variables:
      ansible_host: node2.example.com
      stage: prod
    enabled: true
    state: present

- name: Run job template, waiting for completion
  awx.awx.job_launch:
    controller_host: "{{ controller_host }}"
    controller_username: admin
    controller_password: "{{ controller_password }}"
    job_template: Create Web Content
    wait: true

- name: Run ad-hoc command to get Webserver content
  awx.awx.ad_hoc_command:
    controller_host: "{{ controller_host }}"
    controller_username: admin
    controller_password: "{{ controller_password }}"
    inventory: Workshop Inventory
    limit: "node1,node2,node3"
    module_name: command
    module_args: curl -s http://{{ ansible_host }}
    execution_environment: Default execution environment
    credential: Workshop Credentials
