---

- name: Create project folder according to Lab guide
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/ansible-files"
    state: directory
    mode: "0755"

- name: Create directory structure according to Lab guide
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/ansible-files/{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - group_vars
    - host_vars
    - roles
    - files
    - templates

- name: Create directory structure for role exercise according to Lab guide
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/ansible-files/roles/apache-webserver/{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - tasks
    - handlers
    - templates
    - files

- name: Copy playbooks to destination
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/ansible-files/"
    mode: "0644"
  loop:
    - apache.yml
    - check_httpd.yml
    - deploy_index_html.yml
    - facts.yml
    - ftpserver.yml
    - loop_users.yml
    - motd-facts.yml
    - service_state.yml
    - setup.yml
    - setup_filter.yml
    - test_apache_role.yml
    - user_id.yml

- name: Copy variable files
  ansible.builtin.copy:
    src: "{{ item.file }}"
    dest: "{{ ansible_user_dir }}/ansible-files/{{ item.dest }}"
    mode: "0644"
  loop:
    - file: web.yml
      dest: group_vars
    - file: node2.yml
      dest: host_vars
  loop_control:
    label: "{{ item.file }}"

- name: Copy files referenced in playbooks to global files folder
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/ansible-files/files"
    mode: "0644"
  loop:
    - web.html
    - prod_web.html
    - dev_web.html

- name: Copy templates referenced in playbooks to global templates folder
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/ansible-files/templates"
    mode: "0644"
  loop:
    - motd-facts.j2

- name: Copy all files for role exercise to designated directory structure
  ansible.builtin.copy:
    src: "{{ item.file }}"
    dest: "{{ ansible_user_dir }}/ansible-files/roles/apache-webserver/{{ item.dest }}"
    mode: "0644"
  loop:
    - file: tasks-main.yml
      dest: tasks/main.yml
    - file: handlers-main.yml
      dest: handlers/main.yml
    - file: vhost.conf.j2
      dest: templates/vhost.conf.j2
    - file: role-web.html
      dest: files/web.html
  loop_control:
    label: "{{ item.file }}"

# New inventory group needed for Exercise 1.5
- name: Add additional group with existing host to lab inventory
  ansible.builtin.blockinfile:
    path: "{{ ansible_user_dir }}/lab_inventory/hosts"
    block: |
        [ftpserver]
        node2 ansible_host={{ lookup('ini', 'node2 re=yes section=web file=' + ansible_user_dir + '/lab_inventory/hosts') }}
  become: true
