---

- name: Create project folder according to Lab guide
  file:
    path: "{{ ansible_user_dir }}/ansible-files"
    state: directory

- name: Create directory structure according to Lab guide
  file:
    path: "{{ ansible_user_dir }}/ansible-files/{{ item }}"
    state: directory
  loop:
    - group_vars
    - host_vars
    - roles
    - files
    - templates

- name: Create directory structure for role exercise according to Lab guide
  file:
    path: "{{ ansible_user_dir }}/ansible-files/roles/apache_vhost/{{ item }}"
    state: directory
  loop:
    - tasks
    - handlers
    - templates
    - files

- name: Copy playbooks to destination
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir}}/ansible-files/"
  loop:
    - apache.yml
    - deploy_index_html.yml
    - facts.yml
    - ftpserver.yml
    - httpd_conf.yml
    - loop_users.yml
    - motd-facts.yml
    - test_apache_role.yml

- name: Copy variable files
  copy:
    src: "{{ item.file }}"
    dest: "{{ ansible_user_dir}}/ansible-files/{{ item.dest }}"
  loop:
    - file: web.yml
      dest: group_vars
    - file: node2.yml
      dest: host_vars

- name: Copy files referenced in playbooks to global files folder
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir}}/ansible-files/files"
  loop:
    - web.html
    - prod_web.html
    - dev_web.html
    - httpd.conf

- name: Copy templates referenced in playbooks to global templates folder
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir}}/ansible-files/templates"
  loop:
    - motd-facts.j2

- name: Copy all files for role exercise to designated directory structure
  copy:
    src: "{{ item.file }}"
    dest: "{{ ansible_user_dir}}/ansible-files/roles/apache_vhost/{{ item.dest }}"
  loop:
    - file: tasks-main.yml
      dest: tasks/main.yml
    - file: handlers-main.yml
      dest: handlers/main.yml
    - file: vhost.conf.j2
      dest: templates/vhost.conf.j2
    - file: vhost_index.html
      dest: files/web.html

# New inventory group needed for Exercise 1.5
- name: Add additional group with existing host to lab inventory 
  blockinfile:
    path: "{{ ansible_user_dir}}/lab_inventory/hosts"
    block: |
        [ftpserver]
        node2 ansible_host={{ lookup('ini', 'node2 re=yes section=web file=' + ansible_user_dir + '/lab_inventory/hosts') }}
  become: yes

# Copy lab inventory to demonstrate Ansible Vault in Workshop, this file contains a password
- name: Copy Lab Inventory to home directory
  copy:
    src: "{{ ansible_user_dir }}/lab_inventory/hosts"
    dest: "{{ ansible_user_dir }}/inventory"
